### ISSUE TITLE
Compiling help - what is D:/parser ?

### ISSUE THREAD

**Issue by prplnorangesoda** [Mark-Prime/Melies#2]
Hi! ShearsTF pointed me towards this project as I was looking for a demo recorder.

I was trying to compile this project, but I'm getting an error as there's a dependency in Cargo.toml that references a library on your windows hard drive.

Could you add this to the project / crates.io, please? :heart: 
```text
lucy@arch-linux-desktop ~/c/M/src-tauri (main) [101]> cargo build --verbose
    Updating crates.io index
error: failed to get `tf-demo-parser` as a dependency of package `melies v1.2.3 (/home/lucy/code/Melies/src-tauri)`

Caused by:
  failed to load source for dependency `tf-demo-parser`

Caused by:
  Unable to update /home/lucy/code/Melies/src-tauri/D:/parser

Caused by:
  failed to read `/home/lucy/code/Melies/src-tauri/D:/parser/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by Mark-Prime** [comment]
This was an issue that came up due to the crate for tf-demo-parser not being up to date with the repo itself. 

I've now added the repo for the parser as a submodule so it should be easier to spin up as a contributor.
